# Generated by Django 4.0.6 on 2022-07-26 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_consultorio_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
