# Generated by Django 4.0.6 on 2022-07-26 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_administrador_idcuenta_alter_doctor_idcuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='correo',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='idcuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuenta'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='idcuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuenta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idcuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuenta'),
        ),
    ]
